[package]
name = "enigma"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

[dependencies]
nom = "4.1.1"
num-bigint = "0.2.1"
compress = "0.1.2"
num = "0.2.0"
once_cell = "0.1.6"
parking_lot = "0.7.0"
time = "0.1.40"
